import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
<NavBar></NavBar>  
<h1>Hello {{name}}</h1>
<h1>HELLO {{name}}</h1>
<h1>HELLO {{name}}</h1>
<h1>HELLO {{name}}</h1>
<h1>HELLO {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
<h1>Hello {{name}}</h1>
}}
  
  `
})
export class AppComponent { name = 'Angular'; }
